apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus-ingress
  annotations:
    cert-manager.io/cluster-issuer: issuer

spec:
  ingressClassName: nginx

  rules:
    - host: app.gatus.ibrahimali.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatus-svc
                port:
                  number: 80

  tls:
    - hosts:
        - app.gatus.ibrahimali.co.uk
      secretName: app-gatus-tls