name: Infrastructure Deployment Workflow

on:
    push:
        paths:
          - "infra/**"
          - "cert-manager/**"
    workflow_dispatch:

permissions:
    id-token: write
    contents: read 

env:
    AWS_REGION: eu-west-2
    TF_VERSION: v1.15.1
    CLUSTER_NAME: gatus-eks-cluster

concurrency:
    group: terraform-deploy
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./infra

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            role-to-assume: ${{ secrets.OIDC_ACTIONS_ROLE }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Format Check
          run: terraform fmt -check -recursive 

        - name: Terraform Validate
          run: terraform validate

        - name: Infrastructure Security Scan
          uses: bridgecrewio/checkov-action@v12
          with:
            framework: terraform
            soft_fail: true

        - name: Terraform Plan
          run: terraform plan -input=false -out=tfplan

        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan

        - name: Authenticate into the Cluster
          run: |
            aws eks update-kubeconfig \
            --region ${{ env.AWS_REGION }} \
            --name ${{ env.CLUSTER_NAME }}
          
        - name: Deploy Clusterissuer in Cluster
          run: kubectl apply -f issuer.yaml
          working-directory: ./cert-manager

        - name: Wait for Clusterissuer
          run: |
            kubectl wait \
            --for=condition=Ready \
            clusterissuer/issuer \
            --timeout=300s

        - name: Wait For Argo CD TLS Certificate
          run: |
            kubectl wait \
            --namespace argo-cd \
            --for=condition=Ready \
            certificate/argocd-ingress-tls \
            --timeout=5m

            echo "Argo CD ingress certificate is Ready!"

        - name: Get Argo CD initial password
          id: argocd-password
          run: |
            PASSWORD=$(kubectl -n argo-cd get secret argocd-initial-admin-secret \
            -o jsonpath="{.data.password}" | base64 -d)

            echo "::add-mask::$PASSWORD"
            echo "password=$PASSWORD" >> "$GITHUB_OUTPUT"

        - name: Install Argo CD CLI
          uses: imajeetyadav/argocd-cli@v2
          with:
            version: latest

        - name: Log into Argo CD
          run: |
            argocd login ${{ secrets.ARGOCD_SERVER }} \
              --username ${{ secrets.ARGOCD_USERNAME }} \
              --password "${{ steps.argocd-password.outputs.password }}" \
              --grpc-web

        - name: Deploy gatus application on Argo CD
          working-directory: ./argo-cd
          run: |
            kubectl apply -f gatus-argo.yaml

        - name: Wait for sync to complete
          run: |
            argocd app wait gatus \
              --sync \
              --health \
              --grpc-web

        - name: Verify deployment health
          run: |
            curl -f https://gatus.ibrahimali.co.uk