name: Infrastructure Deployment Workflow

on:
    push:
        paths:
          - "infra/**"
    workflow_dispatch:

permissions:
    id-token: write
    contents: read 

env:
    AWS_REGION: eu-west-2
    TF_VERSION: v1.15.1

concurrency:
    group: terraform-deploy
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./infra

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6
          with:
            role-to-assume: ${{ secrets.OIDC_ACTIONS_ROLE }}
            aws-region: ${{ env.AWS_REGION }}

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v4
          with:
            terraform_version: ${{ env.TF_VERSION }}

        - name: Terraform Init
          run: terraform init

        - name: Terraform Format Check
          run: terraform fmt -recursive 

        - name: Terraform Validate
          run: terraform validate

        - name: Infrastructure Security Scan
          uses: bridgecrewio/checkov-action@v12
          with:
            framework: terraform
            soft_fail: true

        - name: Terraform Plan
          run: terraform plan -input=false -out=tfplan

        - name: Terraform Apply
          run: terraform apply -auto-approve tfplan